#!/usr/bin/env python3

#https://oeis.org/A005132

#a(0) = 0; for n > 0, a(n) = a(n-1) - n if nonnegative and not already in the sequence, otherwise a(n) = a(n-1) + n.

import matplotlib.animation as ani
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import random
import sys
import math


fig = plt.figure()
ax = plt.axes(xlim=(0,0), ylim=(0,0))
plt.title("Recaman's Sequence")

seq = []
def nextValue():

     if len(seq) == 0:
         print("Recamen(%d) = %d" % (len(seq), 0))
         seq.append(0)
         return

     val = seq[-1] - len(seq)
     if val < 0 or val in seq:
         val = seq[-1] + len(seq)
     print("Recamen(%d) = %d" % (len(seq), val))
     seq.append(val)
     return


xdata = []


count = 0
def animate(i=int):
    global count
    grp_size = int(math.exp(count**.3))
    count += 1
    initial = len(seq)

    for v in range(0,grp_size): #Do grp_size between updates
        nextValue()
        xdata.append(len(seq))

    ax.set_ylim([min(seq),max(seq)])
    ax.set_xlim([0,len(seq)])

    return plt.scatter(xdata[initial:-1],seq[initial:-1],s=1,c='Blue')

animator = ani.FuncAnimation(fig, animate, interval = 10)
plt.show()
