#!/usr/bin/env python3

import matplotlib.animation as ani
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import random
import sys


fig = plt.figure()
ax = plt.axes(xlim=(0,0), ylim=(0,0))
plt.title('Liouville Sums')


#Get the number of factors from 'number', if even number of factors add 1 to tally, if odd subtract 1

prime_list = [2]
def nextValue(number,tally):
     factors = [1] #1 is always a factor

     new_number = number
     for i in prime_list:
         #print("Check ",i)
         while new_number % i == 0:
             factors.append(i)
             new_number = new_number/i

     if len(factors) == 1:
         prime_list.append(number)
         factors.append(number)

     #print(number, len(factors), len(factors) % 2, factors)

     #Self check
     #if number != np.prod(factors):
     #    sys.exit(1)

     if len(factors) % 2 == 0:
         return tally-1
     else:
         return tally+1

xdata, ydata = [0,1], [0,0]
my_line, = ax.plot([], [])
my_line.set_data([],[])


count = 0
def animate(i=int):
    global count
    grp_size = 1000
    n = count*grp_size
    count += 1

    for v in range(0,grp_size): #Do grp_size between updates
        xdata.append(n+v+2)
        ydata.append(nextValue(n+v+2,ydata[-1]))

    ax.set_ylim([min(ydata),max(ydata)])
    ax.set_xlim([0,n+grp_size])

    my_line.set_data(xdata, ydata)


    return my_line,

animator = ani.FuncAnimation(fig, animate, interval = 1)
plt.show()
